import { z } from "zod";

export const mappings = {
  // Finance
  "financial analysis": "finance",
  "corporate finance": "finance",
  valuation: "valuation",
  "financial modeling": "excel",
  accounting: "accounting",
  "investment banking": "finance",
  "private equity": "finance",
  "venture capital": "finance",
  "capital markets": "finance",
  "risk management": "risk",
  lbo: "finance",
  dcf: "valuation",
  "m&a": "finance",
  "mergers and acquisitions": "finance",
  "portfolio management": "finance",

  // Operations
  "supply chain": "supplychain",
  "operations management": "operations",
  logistics: "logistics",
  procurement: "procurement",
  "process improvement": "process",
  "six sigma": "sixsigma",
  lean: "lean",
  "project management": "project",
  "inventory management": "supplychain",
  "quality control": "operations",
  kaizen: "lean",
  "operational excellence": "operations",

  // Strategy & Consulting
  strategy: "strategy",
  "management consulting": "consulting",
  "market entry": "strategy",
  "growth strategy": "strategy",
  "business case": "case",

  // General Business
  marketing: "marketing",
  sales: "sales",
  leadership: "leadership",
  ethics: "ethics",
  economics: "economics",
  "data analysis": "analytics",
  excel: "excel",
  tableau: "tableau",

  // Computer Science & Technical
  "data structures": "datastructures",
  algorithms: "algorithm",
  "system design": "systemdesign",
  databases: "database",
  "operating systems": "os",
  "computer networks": "network",
  oops: "oop",
  "object oriented programming": "oop",
  java: "java",
  python: "python",
  javascript: "javascript",
  "c++": "cplusplus",
  "c programming": "c",
  react: "react",
  "node.js": "nodejs",
  nodejs: "nodejs",
  sql: "mysql",
  mongodb: "mongodb",
  postgresql: "postgresql",
  aws: "amazonwebservices",
  azure: "azure",
  "cloud computing": "googlecloud",
  docker: "docker",
  kubernetes: "kubernetes",
  git: "git",
  "version control": "git",
  "machine learning": "tensorflow",
  "artificial intelligence": "tensorflow",
  "deep learning": "pytorch",
  "web development": "html5",
  "frontend": "react",
  "backend": "nodejs",
  "full stack": "javascript",
  devops: "docker",
  "software engineering": "git",
  "problem solving": "algorithm",
  "competitive programming": "cplusplus",
  "dynamic programming": "algorithm",
  "graph algorithms": "algorithm",
  "tree data structures": "datastructures",
  arrays: "datastructures",
  "linked lists": "datastructures",
  "stacks and queues": "datastructures",
  "hash tables": "datastructures",
  "sorting algorithms": "algorithm",
  "searching algorithms": "algorithm",
  "time complexity": "algorithm",
  "space complexity": "algorithm",
  "big o notation": "algorithm",
  rest: "nodejs",
  "api design": "nodejs",
  microservices: "docker",
  "distributed systems": "kubernetes",
  redis: "redis",
  kafka: "apachekafka",
  "message queues": "rabbitmq",
  "load balancing": "nginx",
  caching: "redis",
  "database design": "mysql",
  "sql queries": "mysql",
  "nosql": "mongodb",
  "data modeling": "database",
  "software testing": "jest",
  "unit testing": "jest",
  "integration testing": "selenium",
  "test driven development": "jest",
  agile: "jira",
  scrum: "jira",
  "ci/cd": "jenkins",
  "continuous integration": "jenkins",
  "continuous deployment": "jenkins",
  powerbi: "powerbi",
};

export const feedbackSchema = z.object({
  totalScore: z.number(),
  categoryScores: z.tuple([
    z.object({
      name: z.literal("Communication Skills"),
      score: z.number(),
      comment: z.string(),
    }),
    z.object({
      name: z.literal("Business Acumen"),
      score: z.number(),
      comment: z.string(),
    }),
    z.object({
      name: z.literal("Analytical Thinking"),
      score: z.number(),
      comment: z.string(),
    }),
    z.object({
      name: z.literal("Cultural Fit"),
      score: z.number(),
      comment: z.string(),
    }),
    z.object({
      name: z.literal("Confidence and Clarity"),
      score: z.number(),
      comment: z.string(),
    }),
  ]),
  strengths: z.array(z.string()),
  areasForImprovement: z.array(z.string()),
  finalAssessment: z.string(),
});

export const interviewCovers = [
  "/covers/mckinsey.png",
  "/covers/bcg.png",
  "/covers/bain.png",
  "/covers/goldman.png",
  "/covers/jpmorgan.png",
  "/covers/morganstanley.png",
  "/covers/deloitte.png",
  "/covers/accenture.png",
  "/covers/amazon.png",
  "/covers/google.png",
  "/covers/blackrock.png",
  "/covers/citadel.png",
];

export const dummyInterviews: Interview[] = [
  {
    id: "1",
    userId: "user1",
    role: "Investment Banking Associate",
    type: "Technical Finance",
    focusAreas: ["Valuation", "Financial Modeling", "M&A", "Accounting"],
    level: "MBA Associate",
    questions: ["Walk me through a DCF valuation."],
    finalized: false,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "2",
    userId: "user1",
    role: "Operations Manager",
    type: "Operations Case",
    focusAreas: ["Supply Chain", "Process Improvement", "Lean", "Logistics"],
    level: "Senior Manager",
    questions: ["How would you optimize a bottleneck in a manufacturing plant?"],
    finalized: false,
    createdAt: "2024-03-14T15:30:00Z",
  },
];
